### ISSUE TITLE
DOCTYPE declaration cannot be parsed

### ISSUE THREAD

**Issue by misitoth** [nashwaan/xml-js#13]
I want to convert standard MLP (Mobile Positioning Protocol) xml to JSON and back.
Here is the first 3 line:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svc_init SYSTEM "MLP_SVC_INIT_300.DTD" [<!ENTITY % extension SYSTEM "PIF_EXTENSION_100.DTD">%extension;]>
<svc_init ver="3.0.0"><hdr ver="3.0.0">

After it is converted to JSON:
{
      "_declaration": {
            "_attributes": {
                  "version": "1.0",
                  "encoding": "UTF-8"
            }
      },
      "svc_init": {
            "_attributes": {
                  "ver": "3.0.0"
            }

convert.xml2json(xml, { compact: true, spaces: 6, ignoreCdata: false });
I lost !DOCTYPE.

Can you add ignoreDoctype to the code?

**Comment by nashwaan** [comment]
Sorry, I don't understand the issue here properly.

The first line `%extension;]>` in your example is not a proper xml format.

Also, do you need `ignoreDoctype` to keep the `<!DOCTYPE>`? What do you expect the output json to look like?

**Comment by misitoth** [comment]
!DOCTYPE is valid XML tag, but during the convert.xml2json call parser doesn't parse it and after the conversation we lost the information from that tag. Can you keep !DOCTYPE field in JSON and after json2xml? I propose ingoreDoctype in the options and parser can convert !DOCTYPE like ![CDATA]. 

Example xml was't visible in my first comment.
'<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE svc_init SYSTEM "MLP_SVC_INIT_300.DTD">'

So the second line is doctype of MLP(Mobile Location Protocol), I would like to keep in the conversation.

My proposal in JSON (compact mode) is following:
{ "_doctype" : "scv_init SYSTEM MLP_SVC_INIT_300.DTD"}

**Comment by misitoth** [comment]
`<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE svc_init SYSTEM "MLP_SVC_INIT_300.DTD" [<!ENTITY % extension SYSTEM "PIF_EXTENSION_100.DTD">%extension;]>`

**Comment by nashwaan** [comment]
Ok now I see the issue. Thanks for providing clear example.

I am working on adding support for !DOCTYPE. Currently, I get this output (not published):
```json
{"_doctype": " svc_init SYSTEM \"MLP_SVC_INIT_300.DTD\" [<!ENTITY % extension SYSTEM \"PIF_EXTENSION_100.DTD\">%extension;]"
}
```
As you can see, ENTITY is not parsed.
I prefer to produce more meaningful result. Something like:
```json
{"_doctype": {
    "name_": "svc_init SYSTEM \"MLP_SVC_INIT_300.DTD\"",
     "extension" : "SYSTEM \"PIF_EXTENSION_100.DTD\""
    }
}
```
It seems the content of DOCTYPE is DTD which I am not very familiar with. I need to find time to study it in order to generate meaningful output.

**Comment by DenisCarriere** [comment]
👍 +1 This issue, I've ran into the same problem.

@nashwaan your proposal by adding `_doctype` would solve this, except an easier solution would be to extend it using the `_comment` property since it's the closest one to an inner text without adding any new properties to `xml-js`.

## DOCTYPE (proposed)
Here's my XML example I would like to convert from JSON to XML.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "Note.dtd">
```

```javascript
const json = {
  _declaration: {_attributes: { version: '1.0', encoding: 'utf-8' }},
  _doctype: {
    _comment: 'note SYSTEM "Note.dtd"'
  },
}
const xml = convert.js2xml(json, { compact: true })
```

## DOCTYPE + ENTITY (proposed)

There is also `!ENTITY` in `!DOCTYPE` which is described here: https://www.w3schools.com/xml/xml_dtd.asp. Might need to include an extra params (`_entity`) to support that as well. Entities are typically (always?) used in a list.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ENTITY nbsp "&#xA0;">
<!ENTITY writer "Writer: Donald Duck.">
<!ENTITY copyright "Copyright: W3Schools.">
]>
```

```javascript
const json = {
  _declaration: {_attributes: { version: '1.0', encoding: 'utf-8' }},
  _doctype: {
    _comment: 'note',
    _entity: [
      {_comment: 'nbsp "&#xA0;"'},
      {_comment: 'writer "Writer: Donald Duck."'},
      {_comment: 'copyright "Copyright: W3Schools."'},
    ]
  },
}
const xml = convert.js2xml(json, { compact: true })
```

CC: @misitoth @nashwaan Any thoughts?

**Comment by nashwaan** [comment]
@DenisCarriere , Thank you for your valuable feedback.

I don't think using `_comment` for any DTD content is the best thing to do, because `_comment` should be used for XML comments only (i.e `<!-- some comment -->`). Also, comments can exists in DOCTYPE as well.

I still haven't studied DTD, but my impression is it requires a lot of parsing because of the scenarios it can support. Also, again from my shallow understanding, I think DTD influence how to parse rest of XML contents as it contains some instructions and variables (right?).

What I am planning to do is to put the content of DTD in `_doctype` like I showed before:

```json
{"_doctype": " svc_init SYSTEM \"MLP_SVC_INIT_300.DTD\" [<!ENTITY % extension SYSTEM \"PIF_EXTENSION_100.DTD\">%extension;]"
}
```

And if any needs further processing, then he can use DTD parser like https://github.com/calibr/dtd-file.

Or if you are satisfied with this parser or can recommend me a good parser then I can integrate it with this `xml-js` library.

**Comment by nashwaan** [comment]
I have published v1.1.0 to support `_doctype`.

Please let me know whether this is good or not.

**Comment by DenisCarriere** [comment]
Woot 🎉 Looks like only `1.0.2` is published.

https://www.npmjs.com/package/xml-js

**Comment by nashwaan** [comment]
Ooops.
I have published it now.

**Comment by DenisCarriere** [comment]
Woohoo! Works like a charm.
```javascript
  const json = {
    _declaration: {_attributes: { version: '1.0', encoding: 'utf-8' }},
    ServiceExceptionReport: {
      _attributes: {version: '1.1.1'},
      _doctype: ' ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd"',
      ServiceException: {
        _text: message
      }
    }
  }
  const xml = convert.js2xml(json, { compact: true, spaces: spaces })
```
## Results
```xml
<?xml version="1.0" encoding="utf-8"?>
<ServiceExceptionReport version="1.1.1">
  <!DOCTYPE ServiceExceptionReport SYSTEM "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">
  <ServiceException>foo</ServiceException>
</ServiceExceptionReport>
```

Only odd thing I've noticed is you need to include a blank space in your text field, if not it immediately places the text right after `<!DOCTYPE` (don't know if that was intentional or not).

https://github.com/nashwaan/xml-js/commit/6a6090e7b0452d0852539c848f0b2de900602afe#commitcomment-21926878

**Comment by nashwaan** [comment]
@DenisCarriere Have implemented your suggestion and improved other things (see [release notes](https://github.com/nashwaan/xml-js/releases)). These are now published in v1.2.0.

**Comment by DenisCarriere** [comment]
+1 awesome stuff

**Comment by nashwaan** [comment]
@misitoth What do you think of the new approach published in the latest version?

Do you have any comment or feedback before I close this issue?
