### ISSUE TITLE
js2xml only returns empty string ""

### ISSUE THREAD

**Issue by zaesnet** [nashwaan/xml-js#30]
I installed running version 1.4.2 and tried to run one of the examples from the npm [site ](https://www.npmjs.com/package/xml-js).

Here's the code that I've been trying to run w/o success. Only seem to work xml > js and not the other way around.

var options = {
        spaces: 3,
        compact: false,
        fullTagEmptyElement: true,
        ignoreDeclaration: false,
        ignoreInstruction: false,
        ignoreAttributes: false
};

var xml =
'<?xml version="1.0" encoding="utf-8"?>' +
'<note importance="high" logged="true">' +
'    <title>Happy</title>' +
'    <todo>Work</todo>' +
'    <todo>Play</todo>' +
'</note>';
var someJs = {"a":{"_text":"Hi There"}};

// works as expected
var result1 = convert.xml2js(xml, {compact: true, spaces: 4});

**// doesn't work - only returns empty string**
var restult2 = convert.js2xml(someJs, options);

**Comment by nashwaan** [comment]
Hi zaesnet,

`someJs` constains json object in _compact_ form, but you are supplying `compact: false` in your options. To fix this, you should use `compact: true` in your options:
```js
var options = {
spaces: 3,
compact: true,
fullTagEmptyElement: true,
ignoreDeclaration: false,
ignoreInstruction: false,
ignoreAttributes: false
};
```

otherwise, your `someJs` should have the input in non-compact form:
```js
{
    "elements": [
        {
            "type": "element",
            "name": "a",
            "elements": [
                {
                    "type": "text",
                    "text": "Hi There"
                }
            ]
        }
    ]
}
```

and then you can keep using `compact: false` option.

For more explanation about the compact vs non-compact form, see [this](https://www.npmjs.com/package/xml-js#compact-vs-non-compact).

**Comment by nashwaan** [comment]
Closing as I don't get further feedback on this.

Will re-open if this didn't solve the problem.
